name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - id: checkout
      uses: actions/checkout@v2

    - id: build
      run: |
        echo "`date "+%Y-%m-%d %H:%M"`" > date.txt
        git add date.txt
        git commit -m ":zap: build at `date "+%Y-%m-%d %H:%M"`" && git push
